import {SEVERITY} from './constants.js';


// config for eslint 8.56.0
/** @type {import('eslint').Linter.FlatConfig} */
export const baseRules = {
	files: ['**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx'],
	rules: {
		'array-callback-return': [SEVERITY.ERROR, {
			allowImplicit: false,
			checkForEach: false,
			allowVoid: false,
		}],

		'constructor-super': SEVERITY.ERROR,
		'for-direction': SEVERITY.ERROR,
		'getter-return': SEVERITY.ERROR,
		'no-async-promise-executor': SEVERITY.ERROR,
		'no-await-in-loop': SEVERITY.WARN,
		'no-class-assign': SEVERITY.ERROR,
		'no-compare-neg-zero': SEVERITY.ERROR,
		'no-cond-assign': SEVERITY.ERROR,
		'no-const-assign': SEVERITY.ERROR,
		'no-constant-binary-expression': SEVERITY.ERROR,
		'no-constant-condition': SEVERITY.ERROR,
		'no-constructor-return': SEVERITY.ERROR,
		'no-debugger': SEVERITY.ERROR,
		'no-dupe-args': SEVERITY.ERROR,
		'no-dupe-class-members': SEVERITY.ERROR,
		'no-dupe-else-if': SEVERITY.ERROR,
		'no-dupe-keys': SEVERITY.ERROR,
		'no-duplicate-case': SEVERITY.ERROR,
		'no-duplicate-imports': SEVERITY.ERROR,
		'no-empty-character-class': SEVERITY.ERROR,
		'no-empty-pattern': SEVERITY.ERROR,
		'no-ex-assign': SEVERITY.ERROR,
		'no-fallthrough': [SEVERITY.ERROR, {
			allowEmptyCase: true,
		}],
		'no-func-assign': SEVERITY.ERROR,
		'no-import-assign': SEVERITY.ERROR,
		'no-inner-declarations': [SEVERITY.ERROR, 'both'],
		'no-invalid-regexp': SEVERITY.ERROR,
		'no-irregular-whitespace': [SEVERITY.ERROR, {
			skipStrings: true,
			skipRegExps: true,
			skipTemplates: true,
			skipJSXText: true,
		}],
		'no-loss-of-precision': SEVERITY.ERROR,
		'no-misleading-character-class': SEVERITY.ERROR,
		'no-new-native-nonconstructor': SEVERITY.ERROR,
		'no-obj-calls': SEVERITY.ERROR,
		'no-promise-executor-return': [SEVERITY.ERROR, {
			allowVoid: true,
		}],
		'no-prototype-builtins': SEVERITY.ERROR,
		'no-self-assign': SEVERITY.ERROR,
		'no-self-compare': SEVERITY.ERROR,
		'no-setter-return': SEVERITY.ERROR,
		'no-sparse-arrays': SEVERITY.ERROR,
		'no-template-curly-in-string': SEVERITY.ERROR,
		'no-this-before-super': SEVERITY.ERROR,
		'no-undef': SEVERITY.ERROR,
		'no-unexpected-multiline': SEVERITY.ERROR,
		'no-unmodified-loop-condition': SEVERITY.ERROR,
		'no-unreachable': SEVERITY.ERROR,
		'no-unreachable-loop': SEVERITY.ERROR,
		'no-unsafe-finally': SEVERITY.ERROR,
		'no-unsafe-negation': SEVERITY.ERROR,
		'no-unsafe-optional-chaining': [SEVERITY.ERROR, {
			disallowArithmeticOperators: true,
		}],
		'no-unused-private-class-members': SEVERITY.ERROR,
		'no-unused-vars': [SEVERITY.ERROR, {
			vars: 'all',
			varsIgnorePattern: '^_',
			args: 'none',
			caughtErrors: 'all',
			destructuredArrayIgnorePattern: '^_',
			ignoreRestSiblings: true,
		}],
		'no-use-before-define': SEVERITY.ERROR,
		'no-useless-backreference': SEVERITY.ERROR,
		'require-atomic-updates': [SEVERITY.ERROR, {
			allowProperties: true,
		}],
		'use-isnan': SEVERITY.ERROR,
		'valid-typeof': SEVERITY.ERROR,
		'accessor-pairs': SEVERITY.ERROR,
		'arrow-body-style': SEVERITY.OFF,
		camelcase: SEVERITY.WARN,
		'capitalized-comments': SEVERITY.OFF,
		'class-methods-use-this': SEVERITY.OFF,
		complexity: SEVERITY.OFF,
		'consistent-return': SEVERITY.ERROR,
		'consistent-this': SEVERITY.OFF,
		curly: SEVERITY.ERROR,
		'default-case': SEVERITY.ERROR,
		'default-case-last': SEVERITY.ERROR,
		'default-param-last': SEVERITY.OFF,
		'dot-notation': SEVERITY.ERROR,
		eqeqeq: SEVERITY.ERROR,
		'func-name-matching': SEVERITY.OFF,
		'func-names': SEVERITY.OFF,
		'func-style': [SEVERITY.ERROR, 'expression'],
		'grouped-accessor-pairs': [SEVERITY.WARN, 'getBeforeSet'],
		'guard-for-in': SEVERITY.ERROR,
		'id-denylist': SEVERITY.OFF,
		'id-length': SEVERITY.OFF,
		'id-match': SEVERITY.OFF,
		'init-declarations': SEVERITY.OFF,
		'logical-assignment-operators': SEVERITY.WARN,
		'max-classes-per-file': SEVERITY.OFF,
		'max-depth': SEVERITY.OFF,
		'max-lines': SEVERITY.OFF,
		'max-lines-per-function': SEVERITY.OFF,
		'max-nested-callbacks': SEVERITY.OFF,
		'max-params': [SEVERITY.ERROR, 3],
		'max-statements': SEVERITY.OFF,
		'multiline-comment-style': SEVERITY.OFF,
		'new-cap': SEVERITY.OFF,
		'no-alert': SEVERITY.ERROR,
		'no-array-constructor': SEVERITY.OFF,
		'no-bitwise': SEVERITY.OFF,
		'no-caller': SEVERITY.ERROR,
		'no-case-declarations': SEVERITY.ERROR,
		'no-confusing-arrow': SEVERITY.ERROR,
		'no-console': SEVERITY.ERROR,
		'no-continue': SEVERITY.OFF,
		'no-delete-var': SEVERITY.OFF,
		'no-div-regex': SEVERITY.ERROR,
		'no-else-return': SEVERITY.ERROR,
		'no-empty': [SEVERITY.ERROR, {
			allowEmptyCatch: true,
		}],
		'no-empty-function': [SEVERITY.ERROR, {
			allow: ['arrowFunctions'],
		}],
		'no-empty-static-block': SEVERITY.ERROR,
		'no-eq-null': SEVERITY.ERROR,
		'no-eval': SEVERITY.ERROR,
		'no-extend-native': SEVERITY.ERROR,
		'no-extra-bind': SEVERITY.ERROR,
		'no-extra-boolean-cast': SEVERITY.ERROR,
		'no-extra-label': SEVERITY.ERROR,
		'no-extra-semi': SEVERITY.ERROR,
		'no-floating-decimal': SEVERITY.ERROR,
		'no-global-assign': SEVERITY.ERROR,
		'no-implicit-coercion': [SEVERITY.ERROR, {
			boolean: false,
		}],
		'no-implicit-globals': SEVERITY.ERROR,
		'no-implied-eval': SEVERITY.ERROR,
		'no-inline-comments': SEVERITY.OFF,
		'no-invalid-this': SEVERITY.ERROR,
		'no-iterator': SEVERITY.ERROR,
		'no-label-var': SEVERITY.ERROR,
		'no-labels': [SEVERITY.ERROR, {
			allowLoop: true,
		}],
		'no-lone-blocks': SEVERITY.ERROR,
		'no-lonely-if': SEVERITY.ERROR,
		'no-loop-func': SEVERITY.ERROR,
		'no-magic-numbers': [SEVERITY.ERROR, {
			enforceConst: true,
			ignoreArrayIndexes: true,
			ignoreDefaultValues: false,
			ignoreClassFieldInitialValues: false,
			detectObjects: false,
			ignore: [0, 1],
		}],

		// 'no-mixed-operators': SEVERITY.ERROR,
		'no-multi-assign': SEVERITY.OFF,
		'no-multi-str': SEVERITY.ERROR,
		'no-negated-condition': SEVERITY.ERROR,
		'no-nested-ternary': SEVERITY.ERROR,
		'no-new': SEVERITY.ERROR,
		'no-new-func': SEVERITY.ERROR,
		'no-new-wrappers': SEVERITY.ERROR,
		'no-nonoctal-decimal-escape': SEVERITY.ERROR,
		'no-object-constructor': SEVERITY.ERROR,
		'no-octal': SEVERITY.OFF,
		'no-octal-escape': SEVERITY.ERROR,
		'no-param-reassign': [SEVERITY.ERROR, {
			props: false,
		}],
		'no-plusplus': SEVERITY.OFF,
		'no-proto': SEVERITY.ERROR,
		'no-redeclare': SEVERITY.ERROR,
		'no-regex-spaces': SEVERITY.ERROR,
		'no-restricted-exports': SEVERITY.OFF,
		'no-restricted-globals': SEVERITY.OFF,
		'no-restricted-imports': SEVERITY.OFF,
		'no-restricted-properties': SEVERITY.OFF,
		'no-return-assign': SEVERITY.ERROR,
		'no-script-url': SEVERITY.ERROR,
		'no-sequences': SEVERITY.ERROR,
		'no-shadow': [SEVERITY.ERROR, {
			builtinGlobals: false,
			hoist: 'all',
		}],
		'no-ternary': SEVERITY.OFF,
		'no-throw-literal': SEVERITY.ERROR,
		'no-undef-init': SEVERITY.ERROR,
		'no-undefined': SEVERITY.OFF,
		'no-underscore-dangle': SEVERITY.OFF,
		'no-unneeded-ternary': SEVERITY.ERROR,
		'no-unused-expressions': [SEVERITY.ERROR, {
			enforceForJSX: true,
		}],
		'no-unused-labels': SEVERITY.ERROR,
		'no-useless-call': SEVERITY.ERROR,
		'no-useless-catch': SEVERITY.ERROR,
		'no-useless-computed-key': [SEVERITY.ERROR, {
			enforceForClassMembers: true,
		}],
		'no-useless-concat': SEVERITY.ERROR,
		'no-useless-constructor': SEVERITY.ERROR,
		'no-useless-escape': SEVERITY.ERROR,
		'no-useless-rename': SEVERITY.ERROR,
		'no-useless-return': SEVERITY.ERROR,
		'no-var': SEVERITY.ERROR,
		'no-void': SEVERITY.OFF,
		'no-warning-comments': [SEVERITY.WARN, {
			terms: ['TEMP'],
		}],
		'no-with': SEVERITY.ERROR,

		// 'object-shorthand': [SEVERITY.ERROR, 'consistent-as-needed'],
		'object-shorthand': SEVERITY.OFF,
		'one-var': SEVERITY.OFF,
		'one-var-declaration-per-line': [SEVERITY.ERROR, 'initializations'],
		'operator-assignment': SEVERITY.ERROR,
		'prefer-arrow-callback': SEVERITY.ERROR,
		'prefer-const': [SEVERITY.ERROR, {
			ignoreReadBeforeAssign: true,
		}],
		'prefer-destructuring': SEVERITY.OFF,
		'prefer-exponentiation-operator': SEVERITY.ERROR,
		'prefer-named-capture-group': SEVERITY.ERROR,
		'prefer-numeric-literals': SEVERITY.OFF,
		'prefer-object-has-own': SEVERITY.ERROR,
		'prefer-object-spread': SEVERITY.ERROR,
		'prefer-promise-reject-errors': SEVERITY.OFF,
		'prefer-regex-literals': SEVERITY.OFF,
		'prefer-rest-params': SEVERITY.ERROR,
		'prefer-spread': SEVERITY.ERROR,
		'prefer-template': SEVERITY.ERROR,
		'quote-props': [SEVERITY.ERROR, 'as-needed', {
			keywords: false,
			numbers: false,
		}],
		radix: [SEVERITY.ERROR, 'as-needed'],
		'require-await': SEVERITY.ERROR,
		'require-unicode-regexp': SEVERITY.OFF,
		'require-yield': SEVERITY.OFF,
		'sort-imports': SEVERITY.OFF,
		'sort-keys': SEVERITY.OFF,
		'sort-vars': SEVERITY.OFF,
		'spaced-comment': SEVERITY.ERROR,
		'symbol-description': SEVERITY.ERROR,
		'vars-on-top': SEVERITY.ERROR,
		yoda: [SEVERITY.ERROR, 'never', {
			exceptRange: true,
		}],

		'array-bracket-newline': SEVERITY.OFF, // USE STYLISTIC
		'array-bracket-spacing': SEVERITY.OFF, // USE STYLISTIC
		'array-element-newline': SEVERITY.OFF, // USE STYLISTIC
		'arrow-parens': SEVERITY.OFF, // USE STYLISTIC,
		'arrow-spacing': SEVERITY.OFF, // USE STYLISTIC,
		'block-spacing': SEVERITY.OFF, // USE STYLISTIC,
		'brace-style': SEVERITY.OFF, // USE STYLISTIC,
		'comma-dangle': SEVERITY.OFF, // USE STYLISTIC,
		'comma-spacing': SEVERITY.OFF, // USE STYLISTIC,
		'comma-style': SEVERITY.OFF, // USE STYLISTIC,
		'computed-property-spacing': SEVERITY.OFF, // USE STYLISTIC,
		'dot-location': SEVERITY.OFF, // USE STYLISTIC,
		'eol-last': SEVERITY.OFF, // USE STYLISTIC,
		'func-call-spacing': SEVERITY.OFF, // USE STYLISTIC,
		'function-call-argument-newline': SEVERITY.OFF, // USE STYLISTIC,
		'function-paren-newline': SEVERITY.OFF, // USE STYLISTIC,
		'generator-star-spacing': SEVERITY.OFF, // USE STYLISTIC,
		'implicit-arrow-linebreak': SEVERITY.OFF, // USE STYLISTIC,
		indent: SEVERITY.OFF, // USE STYLISTIC,
		'jsx-quotes': SEVERITY.OFF, // USE STYLISTIC,
		'key-spacing': SEVERITY.OFF, // USE STYLISTIC,
		'keyword-spacing': SEVERITY.OFF, // USE STYLISTIC,
		'line-comment-position': SEVERITY.OFF, // USE STYLISTIC,
		'linebreak-style': SEVERITY.OFF, // USE STYLISTIC,
		'lines-around-comment': SEVERITY.OFF, // USE STYLISTIC,
		'lines-between-class-members': SEVERITY.OFF, // USE STYLISTIC,
		'max-len': SEVERITY.OFF, // USE STYLISTIC,
		'max-statements-per-line': SEVERITY.OFF, // USE STYLISTIC,
		'multiline-ternary': SEVERITY.OFF, // USE STYLISTIC,
		'new-parens': SEVERITY.OFF, // USE STYLISTIC,
		'newline-per-chained-call': SEVERITY.OFF, // USE STYLISTIC,
		'no-extra-parens': SEVERITY.OFF, // USE STYLISTIC,
		'no-mixed-spaces-and-tabs': SEVERITY.OFF, // USE STYLISTIC,
		'no-multi-spaces': SEVERITY.OFF, // USE STYLISTIC,
		'no-multiple-empty-lines': SEVERITY.OFF, // USE STYLISTIC,
		'no-tabs': SEVERITY.OFF, // USE STYLISTIC,
		'no-trailing-spaces': SEVERITY.OFF, // USE STYLISTIC,
		'no-whitespace-before-property': SEVERITY.OFF, // USE STYLISTIC,
		'nonblock-statement-body-position': SEVERITY.OFF, // USE STYLISTIC,
		'object-curly-newline': SEVERITY.OFF, // USE STYLISTIC,
		'object-curly-spacing': SEVERITY.OFF, // USE STYLISTIC,
		'object-property-newline': SEVERITY.OFF, // USE STYLISTIC,
		'operator-linebreak': SEVERITY.OFF, // USE STYLISTIC,
		'padded-blocks': SEVERITY.OFF, // USE STYLISTIC,
		'padding-line-between-statements': SEVERITY.OFF, // USE STYLISTIC,
		quotes: SEVERITY.OFF, // USE STYLISTIC,
		'rest-spread-spacing': SEVERITY.OFF, // USE STYLISTIC,
		semi: SEVERITY.OFF, // USE STYLISTIC,
		'semi-spacing': SEVERITY.OFF, // USE STYLISTIC,
		'semi-style': SEVERITY.OFF, // USE STYLISTIC,
		'space-before-blocks': SEVERITY.OFF, // USE STYLISTIC,
		'space-before-function-paren': SEVERITY.OFF, // USE STYLISTIC,
		'space-in-parens': SEVERITY.OFF, // USE STYLISTIC,
		'space-infix-ops': SEVERITY.OFF, // USE STYLISTIC,
		'space-unary-ops': SEVERITY.OFF, // USE STYLISTIC,
		'switch-colon-spacing': SEVERITY.OFF, // USE STYLISTIC,
		'template-curly-spacing': SEVERITY.OFF, // USE STYLISTIC,
		'template-tag-spacing': SEVERITY.OFF, // USE STYLISTIC,
		'unicode-bom': SEVERITY.OFF, // USE STYLISTIC,
		'wrap-iife': SEVERITY.OFF, // USE STYLISTIC,
		'wrap-regex': SEVERITY.OFF, // USE STYLISTIC,
		'yield-star-spacing': SEVERITY.OFF, // USE STYLISTIC,
	},
};
